title: Diego Flores' Website
description: I'm Diego Flores, a Mechanical Engineer at the George Washington University apart of the class of 2029. I am intrested in coding, buidling things, and the legalities behind what it takes to patent inventions. 
show_downloads: true
logo: /assets/img/IMG_7343.jpg
google_analytics:
theme: jekyll-theme-minimal
